name: otatime_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0-23.0.dev

dependencies:
  animations: ^2.0.11
  flutter:
    sdk: flutter
  flutter_cached_transition: ^1.0.1+1
  flutter_svg: ^2.2.0
  flutter_touch_scale: ^1.1.1+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/